### ISSUE TITLE
No themes other than latte

### ISSUE THREAD

**Issue by wantyapps** [Sekki21956/neomutt#2]
I wanted to install the neomutt theme, and went and cloned it. There seems to be only a latte theme (I am using the Mocha version)

**Comment by nekowinston** [comment]
the themes for Frappe/Macchiato/Mocha are in the `neomuttrc`, the latte verion is in the `latte-neomuttrc`.

Neomutt doesn't have full color support, so they reference your terminal colors. Latte is a separate file because of improved contrast.

**Comment by wantyapps** [comment]
Thanks! I didn't really notice the README.md correctly. Anyway, have a
good day Winston! (Will return shortly to the discord)
